### ISSUE TITLE
Missing(?) rows in the configuration file

### ISSUE THREAD

**Issue by BrekiTomasson** [Globox1997/MobZ#17]
If one sorts the configuration file alphabetically, it looks like a couple of fields might be missing. I'm curious to see if this is intentional or if this is an oversight. It seems as if many mobs have a total of four attributes, namely `MobAttack`, `MobLife`, `MobSpawn` and `MobSpawnRate`. However, the following fields do not appear in my configuration file:

- AndriuSpawn
- AndriuSpawnRate
- BabyRavagerSpawn
- BabyRavagerSpawnRate
- BlackBearAttack
- BlackBearLife
- BoarAttack
- BoarLife
- BossSkeletonAttack
- BrownBearAttack
- BrownBearLife
- CookieCreeperAttack
- DeathSpiritSpawn
- DeathSpiritSpawnRate
- DirtyBoarAttack
- DirtyBoarLife
- GoldenChickenAttack
- GoldenChickenLife
- GrassSlimeAttack
- GrassSlimeLife
- IslandKnightSpawn
- IslandKnightSpawnRate
- KingCharlesSpawn
- KingCharlesSpawnRate
- MetalGolemSpawnRate
- NetherSkeletonAttack
- OvergrownSkeletonAttack
- PillagerBossSpawnRate
- SoulCreeperAttack
- WildBoarAttack
- WildBoarLife
- WilliamSpawn
- WilliamSpawnRate
- WithenderAttack
- WithenderSpawnRate

Now, some of them make sense, especially when it comes to summoned mobs and mobs that don't have a "natural" spawn rate, but others make less sense - especially those with missing "life" and "attack" values.

**Comment by Globox1997** [comment]
yeah these missing configs are intentional :) the missing spawn/spawnrate config is for mobs which doesn´t spawn normal so you won´t find them anywhere. the idea is to have a structure (floating castle) like a dungeon where you will find these but I haven´t been able to implement it yet. all passive entities doesn´t have a hp/attack config cause I think it is enough balanced (since you can´t change the vanilla mobs attributes). all missing attackdmg settings are for mobs which are shooting arrows or stuff :D
